export interface JobDescription {
  title: string;
  company: string;
  description: string;
  required_skills?: string[];
  preferred_skills?: string[];
  nice_to_have?: string[];
  min_experience?: number;
  max_experience?: number;
  leadership_required?: boolean;
  seniority?: 'entry' | 'mid' | 'senior' | 'executive'; // From SearchAgent analysis
}

export interface CandidateProfile {
  id?: string;
  candidate_id?: string;
  name: string;
  title?: string;
  company?: string;
  location?: string;
  skills?: string[];
  experience?: string | number;
  education?: string;
  summary?: string;
  matchScore?: number;
  strengths?: string[];
  fitReasons?: string[];
  availability?: string;
  desiredSalary?: string;
  profileUrl?: string;
  resume_url?: string;
  linkedin_url?: string;
  lastUpdated?: string;
  personal?: {
    name: string;
    email?: string;
    phone?: string;
    linkedin?: string;
    github?: string;
    portfolio?: string;
    location?: string;
  };
  analysis?: {
    current_role?: {
      title: string;
      company: string;
    };
    career_trajectory?: {
      years_experience: number;
      current_level: string;
      progression_speed: string;
      trajectory_type: string;
      domain_expertise: string[];
    };
    company_pedigree?: {
      current_company: string;
      tier_level: string;
      company_types: string[];
      recent_companies: string[];
    };
    skills?: {
      technical_skills: string[];
      soft_skills: string[];
      domain_knowledge: string[];
    };
    education?: {
      highest_degree: string;
      institutions: string[];
    };
  };
  searchable_data?: {
    name: string;
    email: string;
    skills: string[];
    experience_level: number;
    location: string;
    current_company: string;
    current_title: string;
    education_level: string;
  };
  interactions?: {
    notes: any[];
    status_updates: any[];
    emails: any[];
  };
  processing?: {
    status: string;
    stage: string;
    last_updated: any;
    error?: string;
  };
  resume_analysis?: {
    career_trajectory: {
      current_level: string;
      progression_speed: string;
      trajectory_type: string;
      domain_expertise: string[];
    };
    leadership_scope?: {
      has_leadership: boolean;
      team_size?: number;
      leadership_level?: string;
    };
    current_role?: string;
    company_pedigree: {
      tier_level: string;
      company_types: string[];
      recent_companies: string[];
    };
    years_experience: number;
    technical_skills: string[];
    soft_skills: string[];
    education: {
      highest_degree: string;
      institutions: string[];
    };
  };
  intelligent_analysis?: {
    executive_summary?: {
      one_line_pitch: string;
    };
    career_trajectory_analysis?: {
      years_experience: number;
      current_level: string;
      promotion_velocity?: string;
      domain_expertise?: string[];
    };
    explicit_skills?: {
      technical_skills: Array<string | { skill: string; confidence?: number }>;
      soft_skills: Array<string | { skill: string; confidence?: number }>;
    };
    inferred_skills?: {
      highly_probable_skills?: Array<{ skill: string; confidence: number }>;
      probable_skills?: Array<{ skill: string; confidence: number }>;
      likely_skills?: Array<{ skill: string; confidence: number }>;
    };
    role_based_competencies?: {
      current_role_competencies?: {
        role: string;
      };
      historical_competencies?: Array<{
        role: string;
        company?: string;
      }>;
    };
    composite_skill_profile?: {
      domain_specialization: string;
    };
  };
  recruiter_insights?: {
    strengths: string[];
    key_themes: string[];
    recommendation: string;
  };
  original_data?: {
    education?: string;
    experience?: string;
    comments?: string[];
  };
  current_role?: string;
  rationale?: {
    overall_assessment: string;
    strengths: string[];
    gaps: string[];
    risk_factors: string[];
  };
  matchReasons?: string[];
  overall_score: number;
  /** ML trajectory prediction from hh-trajectory-svc (Phase 13) */
  mlTrajectory?: MLTrajectoryPrediction;
}

export interface MatchRationale {
  strengths: string[];
  gaps: string[];
  risk_factors: string[];
  overall_assessment: string;
}

/**
 * LLM-generated match rationale for top candidates (TRNS-03).
 * Provides human-readable explanation of candidate-job fit.
 * Generated by backend for top 10 candidates when includeMatchRationale is true.
 */
export interface LLMMatchRationale {
  /** 2-3 sentence summary of why candidate matches */
  summary: string;
  /** Top 2-3 key strengths */
  keyStrengths: string[];
  /** Which signals drove the match */
  signalHighlights: Array<{
    signal: string;
    score: number;
    reason: string;
  }>;
}

/**
 * Signal scores from multi-signal scoring framework.
 * All values are 0-1 normalized.
 * Mirrors backend SignalScores in services/hh-search-svc/src/types.ts
 */
export interface SignalScores {
  /** Vector similarity from hybrid search (0-1 normalized) */
  vectorSimilarity: number;
  /** Level/seniority match alignment (0-1) */
  levelMatch: number;
  /** Specialty match score (0-1) - backend, frontend, fullstack, etc */
  specialtyMatch: number;
  /** Tech stack compatibility score (0-1) */
  techStackMatch: number;
  /** Function alignment score (0-1) - engineering, product, design, etc */
  functionMatch: number;
  /** Career trajectory fit score (0-1) */
  trajectoryFit: number;
  /** Company pedigree score (0-1) */
  companyPedigree: number;
  /** Skills match score (0-1) - for skill-aware searches, optional */
  skillsMatch?: number;
  // Phase 7 signals (all 0-1 normalized, optional)
  /** SCOR-02: Skills exact match score (0-1) */
  skillsExactMatch?: number;
  /** SCOR-03: Skills inferred score (0-1) */
  skillsInferred?: number;
  /** SCOR-04: Seniority alignment score (0-1) */
  seniorityAlignment?: number;
  /** SCOR-05: Recency boost score (0-1) */
  recencyBoost?: number;
  /** SCOR-06: Company relevance score (0-1) */
  companyRelevance?: number;
}

/**
 * Signal weight configuration for scoring.
 * Weights should sum to 1.0.
 * Mirrors backend SignalWeightConfig in services/hh-search-svc/src/signal-weights.ts
 */
export interface SignalWeightConfig {
  vectorSimilarity: number;
  levelMatch: number;
  specialtyMatch: number;
  techStackMatch: number;
  functionMatch: number;
  trajectoryFit: number;
  companyPedigree: number;
  skillsMatch?: number;
  skillsExactMatch?: number;
  skillsInferred?: number;
  seniorityAlignment?: number;
  recencyBoost?: number;
  companyRelevance?: number;
}

export interface CandidateMatch {
  candidate: CandidateProfile;
  score: number;
  similarity: number;
  rationale: MatchRationale;
  /** Individual signal scores contributing to final score (Phase 9) */
  signalScores?: SignalScores;
  /** Signal weights applied for this search (Phase 9) */
  weightsApplied?: SignalWeightConfig;
  /** Role type preset used for scoring (Phase 9) */
  roleTypeUsed?: string;
  /** LLM-generated match rationale for top candidates (TRNS-03) */
  matchRationale?: LLMMatchRationale;
}

export interface SearchInsights {
  total_candidates: number;
  avg_match_score: number;
  top_skills_matched: string[];
  common_gaps: string[];
  market_analysis: string;
  recommendations: string[];
}

export interface SearchResponse {
  success: boolean;
  matches: CandidateMatch[];
  insights: SearchInsights;
  query_time_ms: number;
}

export interface QuickMatchResult {
  candidate_id: string;
  name: string;
  score: number;
  summary: string;
}

// Authentication types
export interface User {
  uid: string;
  email: string | null;
  displayName: string | null;
  photoURL: string | null;
}

export interface AuthContextType {
  user: User | null;
  loading: boolean;
  signIn: (email: string, password: string) => Promise<void>;
  signInWithGoogle: () => Promise<void>;
  signUp: (email: string, password: string) => Promise<void>;
  signOut: () => Promise<void>;
}

// API Response types
export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

// File upload types
export interface UploadProgress {
  progress: number;
  status: 'idle' | 'uploading' | 'completed' | 'error';
  error?: string;
}

// Dashboard analytics types
export interface DashboardStats {
  totalCandidates: number;
  averageScore?: number;
  avgMatchScore?: number;
  activeSearches: number;
  recentSearches?: number;
  topSkills: Array<{ skill: string; count: number }>;
  topCompanies?: Array<{ company: string; count: number }>;
  recentActivity?: {
    searches: number;
    newCandidates: number;
    highMatches: number;
  };
  experienceLevels?: Record<string, number>;
  companyTiers?: Record<string, number>;
}

// Navigation types
export interface NavItem {
  name: string;
  path: string;
  icon: string;
}

// Skill Assessment types
export interface SkillWithEvidence {
  skill: string;
  confidence: number;
  evidence: string[];
  category?: string;
}

export interface InferredSkill {
  skill: string;
  confidence: number;
  reasoning: string;
  skill_category: string;
}

export interface SkillAssessment {
  total_skills: number;
  average_confidence: number;
  skill_categories: Record<string, number>;
  skills: Record<string, SkillWithEvidence>;
  high_confidence_skills: string[];
  medium_confidence_skills: string[];
  low_confidence_skills: string[];
}

export interface SkillMatchData {
  skill: string;
  candidate_confidence: number;
  required_confidence: number;
  match_score: number;
  evidence: string[];
  category: string;
}

export interface SavedSearch {
  id: string;
  userId: string;
  name: string;
  query: {
    query_text?: string;
    filters?: any;
    job_description?: any;
  };
  type: 'candidate' | 'job';
  createdAt: string;
  lastUsed: string;
}

export interface VectorSearchResult {
  candidate_id: string;
  similarity_score: number;
  overall_score?: number;
  profile?: CandidateProfile;
  match_reasons?: string[];
}

/**
 * ML trajectory prediction from hh-trajectory-svc (Phase 13).
 * Provides next role predictions, tenure estimates, and hireability scores.
 */
export interface MLTrajectoryPrediction {
  /** Predicted next role title */
  nextRole: string;
  /** Confidence in next role prediction (0-1) */
  nextRoleConfidence: number;
  /** Predicted tenure range in months */
  tenureMonths: {
    min: number;
    max: number;
  };
  /** Hireability score (0-1) - likelihood to accept offer */
  hireability: number;
  /** Flag indicating low confidence prediction (<0.6) */
  lowConfidence: boolean;
  /** Explanation for uncertainty if lowConfidence is true */
  uncertaintyReason?: string;
}