apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hh-msgs-svc-${SERVICE_ENVIRONMENT}
  labels:
    app: hh-msgs-svc
    environment: ${SERVICE_ENVIRONMENT}
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        autoscaling.knative.dev/maxScale: "${SERVICE_MAX_SCALE}"
        autoscaling.knative.dev/minScale: "${SERVICE_MIN_SCALE}"
        run.googleapis.com/vpc-access-connector: projects/${SERVICE_PROJECT_ID}/locations/${SERVICE_REGION}/connectors/${VPC_CONNECTOR}
        run.googleapis.com/cloudsql-instances: ${SERVICE_PROJECT_ID}:${SERVICE_REGION}:${SQL_INSTANCE_MSGS}
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT}
      timeoutSeconds: 90
      containerConcurrency: ${SERVICE_CONCURRENCY}
      containers:
        - image: ${SERVICE_IMAGE}
          ports:
            - containerPort: ${SERVICE_PORT}
          env:
            - name: NODE_ENV
              value: production
            - name: SERVICE_ENV
              value: ${SERVICE_ENVIRONMENT}
            - name: FIREBASE_PROJECT_ID
              value: ${SERVICE_PROJECT_ID}
            - name: MSGS_DB_HOST
              value: /cloudsql/${SERVICE_PROJECT_ID}:${SERVICE_REGION}:${SQL_INSTANCE_MSGS}
            - name: MSGS_DB_NAME
              value: ${SQL_DATABASE}
            - name: MSGS_DB_USER
              value: ${SQL_USER_OPERATIONS}
            - name: MSGS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ${SECRET_DB_OPERATIONS}
                  key: latest
            - name: MSGS_REDIS_URL
              value: redis://redis.${SERVICE_ENVIRONMENT}.internal:6379
            - name: MSGS_USE_SEED_DATA
              value: "false"
            - name: MSGS_TEMPLATE_DEFAULT_LOCALE
              value: pt-BR
            - name: ENABLE_REQUEST_LOGGING
              value: "true"
            - name: ENABLE_GATEWAY_TOKENS
              value: "false"
            - name: AUTH_MODE
              value: "firebase"
          resources:
            limits:
              cpu: "${SERVICE_CPU}"
              memory: ${SERVICE_MEMORY}
  traffic:
    - latestRevision: true
      percent: 100
