apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hh-rerank-svc-${SERVICE_ENVIRONMENT}
  labels:
    app: hh-rerank-svc
    environment: ${SERVICE_ENVIRONMENT}
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        autoscaling.knative.dev/maxScale: "${SERVICE_MAX_SCALE}"
        autoscaling.knative.dev/minScale: "${SERVICE_MIN_SCALE}"
        run.googleapis.com/vpc-access-connector: projects/${SERVICE_PROJECT_ID}/locations/${SERVICE_REGION}/connectors/${VPC_CONNECTOR}
        run.googleapis.com/vpc-access-egress: all-traffic
        run.googleapis.com/cloudsql-instances: ${SERVICE_PROJECT_ID}:${SERVICE_REGION}:${SQL_INSTANCE}
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT}
      timeoutSeconds: 45
      containerConcurrency: ${SERVICE_CONCURRENCY}
      containers:
        - image: ${SERVICE_IMAGE}
          ports:
            - containerPort: ${SERVICE_PORT}
          env:
            - name: NODE_ENV
              value: production
            - name: SERVICE_ENV
              value: ${SERVICE_ENVIRONMENT}
            - name: FIREBASE_PROJECT_ID
              value: ${SERVICE_PROJECT_ID}
            - name: REDIS_HOST
              value: redis.${SERVICE_ENVIRONMENT}.internal
            - name: REDIS_PORT
              value: "6379"
            - name: TOGETHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ${SECRET_TOGETHER_AI}
                  key: latest
            - name: TOGETHER_API_BASE_URL
              value: https://api.together.xyz/v1
            - name: TOGETHER_MODEL
              value: ${TOGETHER_AI_MODEL}
            - name: RERANK_CACHE_TTL_SECONDS
              value: "180"
            - name: RERANK_MAX_CANDIDATES
              value: "50"
            - name: RERANK_SLA_TARGET_MS
              value: "${TOGETHER_AI_P95_TARGET_MS}"
            - name: ENABLE_GATEWAY_TOKENS
              value: "false"
            - name: AUTH_MODE
              value: "firebase"
          resources:
            limits:
              cpu: "${SERVICE_CPU}"
              memory: ${SERVICE_MEMORY}
  traffic:
    - latestRevision: true
      percent: 100
