apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hh-search-svc-${SERVICE_ENVIRONMENT}
  labels:
    app: hh-search-svc
    environment: ${SERVICE_ENVIRONMENT}
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        autoscaling.knative.dev/maxScale: "${SERVICE_MAX_SCALE}"
        autoscaling.knative.dev/minScale: "${SERVICE_MIN_SCALE}"
        run.googleapis.com/vpc-access-connector: projects/${SERVICE_PROJECT_ID}/locations/${SERVICE_REGION}/connectors/${VPC_CONNECTOR}
        run.googleapis.com/vpc-access-egress: all-traffic
        run.googleapis.com/cloudsql-instances: ${SERVICE_PROJECT_ID}:${SERVICE_REGION}:${SQL_INSTANCE}
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT}
      timeoutSeconds: 90
      containerConcurrency: ${SERVICE_CONCURRENCY}
      containers:
        - image: ${SERVICE_IMAGE}
          ports:
            - containerPort: ${SERVICE_PORT}
          env:
            - name: NODE_ENV
              value: production
            - name: SERVICE_ENV
              value: ${SERVICE_ENVIRONMENT}
            - name: FIREBASE_PROJECT_ID
              value: ${SERVICE_PROJECT_ID}
            - name: REDIS_HOST
              value: 10.159.1.4
            - name: REDIS_PORT
              value: "6378"
            - name: PGVECTOR_HOST
              value: /cloudsql/${SERVICE_PROJECT_ID}:${SERVICE_REGION}:${SQL_INSTANCE}
            - name: PGVECTOR_PORT
              value: "5432"
            - name: PGVECTOR_DATABASE
              value: ${SQL_DATABASE}
            - name: PGVECTOR_USER
              value: ${SQL_USER_ANALYTICS}
            - name: PGVECTOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${SECRET_DB_ANALYTICS}
                  key: latest
            - name: EMBED_SERVICE_URL
              value: ${EMBED_SERVICE_URL}
            - name: RERANK_SERVICE_URL
              value: ${RERANK_SERVICE_URL}
            - name: EVIDENCE_SERVICE_URL
              value: ${EVIDENCE_SERVICE_URL}
            - name: HEALTH_TENANT_ID
              value: tenant-alpha
            - name: ENABLE_REQUEST_LOGGING
              value: "true"
            - name: SEARCH_CACHE_TTL_SECONDS
              value: "180"
            - name: SEARCH_FIRESTORE_FALLBACK
              value: "true"
            - name: ENABLE_GATEWAY_TOKENS
              value: "false"
            - name: AUTH_MODE
              value: "firebase"
          resources:
            limits:
              cpu: "${SERVICE_CPU}"
              memory: ${SERVICE_MEMORY}
  traffic:
    - latestRevision: true
      percent: 100
