-- Grant permissions to hh_app user

-- Grant schema usage
GRANT USAGE ON SCHEMA search TO hh_app;
GRANT USAGE ON SCHEMA taxonomy TO hh_app;
GRANT USAGE ON SCHEMA msgs TO hh_app;
GRANT USAGE ON SCHEMA ops TO hh_app;

-- Grant table permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA search TO hh_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA taxonomy TO hh_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA msgs TO hh_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ops TO hh_app;

-- Grant sequence permissions
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA search TO hh_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA taxonomy TO hh_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA msgs TO hh_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ops TO hh_app;

-- Grant database connection
GRANT CONNECT ON DATABASE headhunter TO hh_app;

-- Grant permissions to hh_analytics user
GRANT CONNECT ON DATABASE headhunter TO hh_analytics;
GRANT USAGE ON SCHEMA search TO hh_analytics;
GRANT SELECT ON ALL TABLES IN SCHEMA search TO hh_analytics;

-- Grant permissions to hh_ops user
GRANT CONNECT ON DATABASE headhunter TO hh_ops;
GRANT USAGE ON SCHEMA search, taxonomy, msgs, ops TO hh_ops;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA search TO hh_ops;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA taxonomy TO hh_ops;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA msgs TO hh_ops;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ops TO hh_ops;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA search TO hh_ops;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA taxonomy TO hh_ops;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA msgs TO hh_ops;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ops TO hh_ops;

-- Set default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA search GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO hh_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA taxonomy GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO hh_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA msgs GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO hh_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ops GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO hh_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA search GRANT USAGE, SELECT ON SEQUENCES TO hh_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA taxonomy GRANT USAGE, SELECT ON SEQUENCES TO hh_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA msgs GRANT USAGE, SELECT ON SEQUENCES TO hh_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ops GRANT USAGE, SELECT ON SEQUENCES TO hh_app;
